name: markdown-linter
on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
      - uses: actions/checkout@v2
      - name: Run Markdown Lint
        uses: actionshub/markdownlint@main
